apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-queue
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8161
      nodePort: 30010
  selector:
    # This defines which pods going to be represented by this service
    # The service becomes network endpoint for either other services 
    # or external users to connect to (browser)
    # Loadbalance traffic across Pods matching
    # this label selector
    app: activemq
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  #type: LoadBalancer
  # use type: ClusterIP  if the service will be only accessed within the K8s clsuter only
  # use type: NodePort is the service will be access outside of the K8s container e.g. webapps that needs to be exposed outside the world
  type: NodePort